# Generated by Django 4.1.4 on 2023-03-31 11:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note_app', '0003_alter_notemodel_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 11, 17, 48, 915796, tzinfo=datetime.timezone.utc)),
        ),
    ]
