# Generated by Django 4.1.4 on 2023-04-12 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0004_notemodel_user_alter_notemodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 12, 32, 5, 802573, tzinfo=datetime.timezone.utc)),
        ),
    ]
